export PGADMIN_DEFAULT_EMAIL="jimmy@1024bees.com"
export PGADMIN_DEFAULT_PASSWORD="password"
docker run -e PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL} -e PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD} dpage/pgadmin4:latest
